"""Framework-neutral file processing services."""

from simple_database_toolkit.build_profile import BML_EDITOR_ENABLED

if BML_EDITOR_ENABLED:
    from .bml_service import (
        BmlFileInfo,
        BmlFolderSnapshot,
        BmlV1SaveRequest,
        BmlV2SaveRequest,
        BmlVersion,
        MaterialRename,
        decode_bml,
        detect_bml_version,
        encode_bml,
        inspect_bml_folder,
        read_v1_texture_ids,
        read_v2_material_names,
        save_bml_v1,
        save_bml_v2,
        set_v1_texture_ids,
        set_v2_material_names,
    )
from .folder_service import FolderCreateRequest, create_folders
from .link_service import (
    CostBand,
    Link,
    LinkGenerationRequest,
    LinkUpdateRequest,
    Objective,
    extract_distance_cost_lut,
    generate_all_links,
    load_lut,
    read_objectives,
    segments_intersect,
    update_changed_links,
)
from .offset_service import (
    FeatureScanRequest,
    OffsetAdjustment,
    OffsetMode,
    OffsetOperation,
    OffsetRequest,
    apply_offset,
    scan_features,
)
from .parent_service import (
    ParentMode,
    ParentRequest,
    check_parent_bml_files,
    check_parent_fields,
    format_parent_content,
    reformat_parents,
    validate_parent_content,
)
from .parking_service import (
    ParkingMode,
    ParkingMove,
    ParkingObjectivePreview,
    ParkingPreview,
    ParkingRequest,
    apply_parking,
    preview_parking,
)
from .replace_service import (
    ReplaceFeatureRequest,
    ReplaceMode,
    replace_features,
    scan_replacements,
)
from .runway_service import (
    CHECK_LABELS,
    HeadingChoice,
    RunwayCheck,
    RunwayMapComparison,
    RunwayMapPath,
    RunwayMapPoint,
    RunwayMapSnapshot,
    RunwayMode,
    RunwayPolygon,
    RunwayRequest,
    build_crossing_pairs,
    build_runway_dim_boxes,
    build_runway_polygons,
    build_taxi_tree,
    calculate_runway_heading,
    check_runways,
    fix_runways,
    point_in_box,
    segment_polygon_crossings,
    segments_intersect as runway_segments_intersect,
    walk_taxi_paths,
)

__all__ = [
    "BmlFileInfo",
    "BmlFolderSnapshot",
    "BmlV1SaveRequest",
    "BmlV2SaveRequest",
    "BmlVersion",
    "CHECK_LABELS",
    "FolderCreateRequest",
    "HeadingChoice",
    "CostBand",
    "FeatureScanRequest",
    "OffsetAdjustment",
    "OffsetMode",
    "OffsetOperation",
    "OffsetRequest",
    "Link",
    "LinkGenerationRequest",
    "LinkUpdateRequest",
    "MaterialRename",
    "Objective",
    "ParentMode",
    "ParentRequest",
    "ParkingMode",
    "ParkingMove",
    "ParkingObjectivePreview",
    "ParkingPreview",
    "ParkingRequest",
    "ReplaceFeatureRequest",
    "ReplaceMode",
    "RunwayCheck",
    "RunwayMapComparison",
    "RunwayMapPath",
    "RunwayMapPoint",
    "RunwayMapSnapshot",
    "RunwayMode",
    "RunwayPolygon",
    "RunwayRequest",
    "apply_offset",
    "apply_parking",
    "build_crossing_pairs",
    "build_runway_dim_boxes",
    "build_runway_polygons",
    "build_taxi_tree",
    "check_parent_bml_files",
    "check_parent_fields",
    "check_runways",
    "create_folders",
    "decode_bml",
    "detect_bml_version",
    "encode_bml",
    "extract_distance_cost_lut",
    "calculate_runway_heading",
    "format_parent_content",
    "fix_runways",
    "generate_all_links",
    "inspect_bml_folder",
    "load_lut",
    "read_objectives",
    "read_v1_texture_ids",
    "read_v2_material_names",
    "reformat_parents",
    "replace_features",
    "scan_features",
    "scan_replacements",
    "preview_parking",
    "point_in_box",
    "save_bml_v1",
    "save_bml_v2",
    "segments_intersect",
    "runway_segments_intersect",
    "segment_polygon_crossings",
    "set_v1_texture_ids",
    "set_v2_material_names",
    "update_changed_links",
    "validate_parent_content",
    "walk_taxi_paths",
]

if not BML_EDITOR_ENABLED:
    __all__ = [name for name in __all__ if name not in {
        "BmlFileInfo", "BmlFolderSnapshot", "BmlV1SaveRequest", "BmlV2SaveRequest",
        "BmlVersion", "MaterialRename", "decode_bml", "detect_bml_version",
        "encode_bml", "inspect_bml_folder", "read_v1_texture_ids",
        "read_v2_material_names", "save_bml_v1", "save_bml_v2",
        "set_v1_texture_ids", "set_v2_material_names",
    }]
